# Generated by Django 5.1.1 on 2024-10-01 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_bags_rating_alter_dress_rating_and_more"),
    ]

    operations = [
        migrations.RunSQL("create extension if not exists pg_trgm"),

    ]