# Generated by Django 5.1.1 on 2024-10-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_users_is_active_alter_users_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
