# Generated by Django 5.1.1 on 2024-10-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_users_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="avatar",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="avatars/"
            ),
        ),
    ]
