# Generated by Django 5.1.1 on 2024-10-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_users_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="userscards",
            name="card_name",
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
    ]
