# Generated by Django 5.1.1 on 2024-10-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_userscards_card_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userscards",
            name="card_token",
        ),
        migrations.AlterField(
            model_name="userscards",
            name="card_number",
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name="userscards",
            name="cvv",
            field=models.IntegerField(max_length=3),
        ),
    ]
