# Generated by Django 5.1.1 on 2024-10-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_remove_userscards_card_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userscards",
            name="cvv",
            field=models.IntegerField(),
        ),
    ]
