# Generated by Django 5.1.1 on 2024-10-06 09:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_alter_userscards_cvv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userscards",
            name="account",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cards",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userscards",
            name="card_number",
            field=models.CharField(
                max_length=16,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Card number must be exactly 16 digits.",
                        regex="^\\d{16}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userscards",
            name="cvv",
            field=models.CharField(
                max_length=3,
                validators=[
                    django.core.validators.RegexValidator(
                        message="CVV must be exactly 3 digits.", regex="^\\d{3}$"
                    )
                ],
            ),
        ),
    ]
