# Generated by Django 5.1.1 on 2024-10-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_alter_userscards_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userscards",
            name="expiration_date",
            field=models.CharField(max_length=5),
        ),
    ]
