# Generated by Django 5.1.1 on 2024-10-06 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_alter_userscards_expiration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userscards",
            name="expiration_date",
            field=models.CharField(
                max_length=5,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Expiration date must be in MM/YY format.",
                        regex="^(0[1-9]|1[0-2])\\/\\d{2}$",
                    )
                ],
            ),
        ),
    ]
